name: Deploy Web App to Firebase Hosting
'on':
  push:
    branches:
      - dev
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth-staging'
        name: 'Authenticate to Google Cloud Staging'
        if: github.ref == 'refs/heads/dev'
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VSELF_DEV }}'
      - id: 'auth-production'
        name: 'Authenticate to Google Cloud Production'
        if: github.ref == 'refs/heads/main'
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VSELF_PROD }}'
      - uses: actions/checkout@v2
      - name: Install Node Modules And Build App
        run: yarn && yarn build && sudo npm i -g firebase-tools
        env:
          NFT_STORAGE_API_KEY: ${{ secrets.NFT_STORAGE_API_KEY }}
          USER_ACCOUNT_ID: ${{ secrets.USER_ACCOUNT_ID }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          MAINNET_USER_ACCOUNT_ID: ${{ secrets.MAINNET_USER_ACCOUNT_ID }}
          MAINNET_PUBLIC_KEY: ${{ secrets.MAINNET_PUBLIC_KEY }}
          MAINNET_PRIVATE_KEY: ${{ secrets.MAINNET_PRIVATE_KEY }}
          ENV_STAT: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
          FIREBASE_AUTH_DOMAIN: ${{ github.ref == 'refs/heads/main' && 'vself-prod.firebaseapp.com' || 'vself-dev.firebaseapp.com' }}
          FIREBASE_DATABASE_URL: 'https://vself-dev-default-rtdb.firebaseio.com'
          FIREBASE_PROJECT_ID: ${{ github.ref == 'refs/heads/main' && 'vself-prod' || 'vself-dev' }}
          FIREBASE_STORAGE_BUCKET: ${{ github.ref == 'refs/heads/main' && 'vself-prod.appspot.com' || 'vself-dev.appspot.com' }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_PROD_SENDER_ID || secrets.FIREBASE_DEV_SENDER_ID }}
          FIREBASE_API_KEY: ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_PROD_API_KEY || secrets.FIREBASE_DEV_API_KEY }}
          FIREBASE_APP_ID: ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_PROD_APP_ID || secrets.FIREBASE_DEV_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_PROD_MEASUREMENT_ID || secrets.FIREBASE_DEV_MEASUREMENT_ID }}
      - name: Deploy Next Server Function To Firebase Staging
        if: github.ref == 'refs/heads/dev'
        run: firebase deploy -P staging --only functions:nextjseurope --force && firebase deploy -P staging --only hosting
      - name: Deploy Next Server Function To Firebase Production
        if: github.ref == 'refs/heads/main'
        run: firebase deploy -P prod --only functions:nextjseurope --force && firebase deploy -P prod --only hosting
